site_name: Programació de geoaplicacions web
site_url: https://gss-mtig.github.io/geo-web-mgeo/
site_description: Programació de geoaplicacions web
site_author: geo-web-mgeo
theme:
  name: 'material'
  language: 'es'
  highlightjs: true
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
repo_url: "https://github.com/gss-mtig/geo-web-mgeo"

nav:
- Home: index.md
- Google Maps JavaScript API: google.md
- ArcGIS API for Javascript: arcgis.md
- OpenLayers: openLayers.md
- Turf: turf.md
- Leaflet: leaflet.md
- MapLibre GL JS (Mapbox GL): maplibre.md

plugins:
  - search
  - macros

extra:
  versions:
    arcgis: 4.32
    openlayers: 10.4.0
    leaflet: 1.9.4
    leaflet_hash: 0.2.1
    leaflet_ajax: 2.1.0
    leaflet_easybutton: 2
    leaflet_draw: 1.0.4
    leaflet_sidebar_v2: 0.4.0
    turf: 7
    bootstrap_icons: 1.11.3


